version: '2.15.1'
  
services:
  ecommerce-shop: 
    container_name: ecommerce-shop
    image: ecommerce-shop
    restart: always
    build: .
    ports: 
      - 8080-8081:8080
    environment: 
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb: 
    container_name: mysqldb
    image: mysql:latest
    restart: always
    environment: 
         MYSQL_DATABASE: shop-db
         MYSQL_ROOT_PASSWORD: root 
    ports: 
        - 3306:3306
    volumes: 
        - .dbdata:/var/lib/mysql